# Generated by Django 5.0.1 on 2024-02-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkself', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
