# Generated by Django 5.0.1 on 2024-02-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkself', '0002_rename_is_admin_buyer_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
