# Generated by Django 5.0.1 on 2024-02-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=191, unique=True)),
                ('nickname', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
